---
CNV:
    pileup:
        MAPQ: 20
        Q: 25
    hetSNP:
        normalVAF: [0.2,0.8]
        minDepth: 15
    coverage:
        minCov: 0
        minPONcov: 50
        maxPONstd: 50
    PONcoverage:
        minCov: 0 # start with no coverage to 
        minVAF: 0.25
        minDepth: 50
        stdFactor: 2  # only exonPositions straighing within std_factor * std around meanCoverage are kept
