bam_folder: 
    - /fast/users/szyskam_c/work/results/P483/bamfinal
workdir: /fast/users/szyskam_c/scratch/develop/PONcoverage # here your results are created
snakedir: /fast/users/szyskam_c/snakes/develop/myCNV
sample_sheet: config/P483_sheet.csv           # sample_sheet relative to script folder
#### ABSOLUTE PATHS ############
paths:
    mystatic: /fast/groups/ag_damm/work/ref/
#### PON #######################
pon_list: PoN/HAEv7_hg38_NovaSeq/Pon_list.txt # path relative to mystatic path
#### REF SECTION ###############
ref:
    genome: genome/gatk/hg38/hg38.fasta
    genome_split: genome/gatk/hg38/split
    dbsnp: dbsnp153
    dbsnp_split: annotation/gatk/hg38/split
    bed_file: bed_files/SureSelect/hg38/SS_HAEv7_hg38_Covered.bed
    bed_file_pad: bed_files/SureSelect/hg38/SS_HAEv7_hg38_Padded.bed
    PONcov: PoN/HAEv7_hg38_NovaSeq/chromCov
cleanup: False
chrom_with_chr: true # whether bam files contain chr in name
# RULES
CNV:
    coverage:
        threads: 6
        MAPQ: 20
        rollingWindowSize: 100  # size of the averager for the coverage tool
        drop_duplicates: true
    PONcoverage:
        normCov: 100 # to what value are coverages normalized#
        stdFactor: 2  # only exonPositions straighing within std_factor * std around meanCoverage are kept
        verbose_output: false
    hetSNP:
        threads: 6
        MAPQ: 20
        Q: 25
        minVAF: 0.0001
        minDepth: 10
    combine:
        threads: 1
        debug: false # also export the left and right rolling window values (L/R)
        na_remove: true
        diff_exp: 4  # the exponent for the diff function --> higher values make steeper peaks
        ddof: 0     # set the degree of freedom (0 seems better)
        cov:
            filter:
                min_cov: 30
                min_PON_cov: 50
                max_PON_std: 50
            normalize: false
            center: true
            expand: 0.25   # after interpolation of rolling data from filtered df into full df, interpolate missing data within this fraction of window size, set 0 if no interpolation is wanted
            rolling_data:
                log2ratio:
                    mean: 250
                covLLH:
                    sum: 250
            LLH:    # parameters for llh computation
                center_range: [-0.6, 0.4]   # the mean of the gaussian is taken from log2ratios within center range
                sigma_factor: 1     # determines the spread of the center gaussian - sigma of center gaussian is std * sigma_factor
            LLH_cutoff:  # data with LLH below threshold are used for L2R-absVAF clustering
                cnv: 0.4   # covLLH
                center: 0.6
                max_diff: 0.1 # the cutoff for the diff used for block collapsing
                min_block_size: 100  # the number of contiguous data to make a block
        snp:
            filter:
                VAF: [0.05,.98]
                minDepth: 15
            fallSNP:
                run: true
                maxFallSNP: 0.4 # after computation, filter out "falling SNPs" with fallSNP > 0.4"
                offVAFwindow: 20
            normalize: true
            center: false
            expand: 0.5
            rolling_data:
                absVAF:
                    mean: 20
                VAF:
                    std: 30
                snpLLH: 
                    sum: 20
                hsnpLLH:
                    sum: 40

            LLH:    # parameters for llh computation
                center_range: [0.4, 0.6]   # the mean of the gaussian is taken from log2ratios within center range
                sigma_factor: 0.5     # determines the spread of the center gaussian - sigma of center gaussian is std * sigma_factor
            LLH_cutoff:  # data with LLH below threshold are used for L2R-absVAF clustering
                    cnv: 0.15
                    center: 0.4
                    max_diff: 0.1
                    min_block_size: 10  # the number of contiguous data to make a block
    cluster:
        LLH_cutoff:  # data with LLH below threshold are used for L2R-absVAF clustering
            covLLH: 
                cnv: 0.45
                center: 0.6
                diff: 0.1

        thresholds: 
            log2ratiomean: [0.55, 0.35, True] # lower and upper threshold for filter_df, if True: value is absolute
            deltaVAFvar: [0.075, 0.025, True]
        cleanup_density: 0.4
        centers: 2
EBFilter:
    run: True
    pon_list: PoN/HAEv7_hg38_NovaSeq/Pon_list.txt # path relative to mystatic path
    use_cache: False
    cache_folder: PoN/HAEv7_hg38_NovaSeq # path relative to mystatic path
    threads:
        pileup: 12
        makeEBcache: 20
        EBscore: 20
        EBsplit_factor: 20 # into how many jobs is makeEBcache divided per chromosome
    params:
        MAPQ: 20   # I guess this should be lower than the mapping quality used for mpileup or not?
        Q: 25
        fitting_penalty: 0.5