bam_folder: 
    - /fast/users/szyskam_c/work/results/P483/bamfinal
workdir: /fast/users/szyskam_c/scratch/develop/PONcoverage # here your results are created
snakedir: /fast/users/szyskam_c/snakes/develop/myCNV
sample_sheet: config/P483_sheet.csv           # sample_sheet relative to script folder
#### ABSOLUTE PATHS ############
paths:
    mystatic: /fast/groups/ag_damm/work/ref/
    scripts: shell  # path relative to the snake folder
#### PON #######################
pon_list: PoN/HAEv7_hg38_NovaSeq/Pon_list.txt # path relative to mystatic path
#### REF SECTION ###############
ref:
    genome: genome/gatk/hg38/hg38.fasta
    genome_split: genome/gatk/hg38/split
    dbsnp: dbsnp153
    dbsnp_split: annotation/gatk/hg38/split
    bed_file: bed_files/SureSelect/hg38/SS_HAEv7_hg38_Covered.bed
    bed_file_pad: bed_files/SureSelect/hg38/SS_HAEv7_hg38_Padded.bed
    PONcov: PoN/HAEv7_hg38_NovaSeq/chromCov
scripts:
    # bedCoverage
    bamCoverage: bamCoverage.mawk
    filterBed: filterBed.mawk
    rollingCoverage: rollingCoverage.mawk
    snpVAF: snpVAF.mawk
    cleanSNP: cleanSNP.mawk
    # EBfilter
    cleanpileup: shell/cleanpileup.mawk
    pile2count: shell/pile2count.mawk
    matrix2EBinput: shell/matrix2EBinput.mawk
    makeponlist: shell/makeponlist.sh
    csv2bed: shell/csv2bed.mawk
    pon2cols: shell/pon2cols.mawk
    reducematrix: shell/matrix_minus_sample.mawk
    reordermatrix: shell/reorder_matrix.mawk
cleanup: False
# RULES
CNV:
    get_coverage:
        threads: 6
        MAPQ: 20
    hetero_snp:
        threads: 6
        MAPQ: 20
        Q: 25
        minVAF: 0.0001
        minDepth: 10
    combine:
        threads: 1
        debug: true
        na_remove: true
        diff_exp: 4
        coverage:
            filter:
                min_cov: 30
                min_PON_cov: 50
                max_PON_std: 100
            normalize: false
            center: true
            expand: 0.2
            data:
                log2ratio:
                    mean: 100
        heteroSNP:
            filter:
                VAF:
                - 0.05
                - 0.95
                minDepth: 30
                minEB: 0.5
            normalize: true
            center: false
            expand: 0.5
            data:
                absVAF:
                    mean: 20
                VAF:
                    std: 20
                deltaVAF:
                    var: 20
                    std: 20
EBFilter:
    run: True
    pon_list: PoN/HAEv7_hg38_NovaSeq/Pon_list.txt # path relative to mystatic path
    use_cache: False
    cache_folder: PoN/HAEv7_hg38_NovaSeq # path relative to mystatic path
    threads:
        pileup: 12
        makeEBcache: 20
        EBscore: 20
        EBsplit_factor: 20 # into how many jobs is makeEBcache divided per chromosome
    params:
        MAPQ: 20   # I guess this should be lower than the mapping quality used for mpileup or not?
        Q: 25
        fitting_penalty: 0.5