bam_folder: 
    - /fast/users/szyskam_c/work/results/P483/bamfinal
workdir: /fast/users/szyskam_c/scratch/develop/PONcoverage # here your results are created
snakedir: /fast/users/szyskam_c/snakes/develop/myCNV
sample_sheet: config/sample_sheet.csv           # sample_sheet relative to script folder
#### ABSOLUTE PATHS ############
paths:
    mystatic: /fast/groups/ag_damm/work/ref/
    scripts: shell  # path relative to the snake folder
#### PON #######################
pon_list: PoN/HAEv7_hg38_NovaSeq/Pon_list.txt # path relative to mystatic path
#### REF SECTION ###############
ref:
    genome: genome/gatk/hg38/hg38.fasta
    genome_split: genome/gatk/hg38/split
    dbsnp: dbsnp153
    dbsnp_split: annotation/gatk/hg38/split
    bed_file: bed_files/SureSelect/hg38/SS_HAEv7_hg38_Covered.bed
    bed_file_pad: bed_files/SureSelect/hg38/SS_HAEv7_hg38_Padded.bed
    chromCov: PoN/HAEv7_hg38_NovaSeq/chromCov
scripts:
    # bedCoverage
    bamCoverage: bamCoverage.mawk
    filterBed: filterBed.mawk
    rollingCoverage: rollingCoverage.mawk
    snpVAF: snpVAF.mawk
    cleanSNP: cleanSNP.mawk
cleanup: False
# RULES
get_coverage:
    threads: 6
    MAPQ: 20
    rollingWindowSize: 100  # size of the averager for the coverage tool
hetero_snp:
    threads: 6
    MAPQ: 20
    Q: 25
    minVAF: 0.0001
    minDepth: 10
combine_pon_coverage:
    threads: 1
    norm_coverage: 250

